name: CI - CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://ghcr.io -u eloiblt --password-stdin

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.3

      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@v3.0.3

      - name: Display GitVersion outputs
        run: |
          echo "SemVer: ${{ steps.version_step.outputs.semVer }}"

      - name: Build
        working-directory: .
        run:
          docker build -t ghcr.io/eloiblt/ubuntu-custom-image:${{ steps.version_step.outputs.semVer }}:latest  .

      - name: Push
        working-directory: .
        run: docker push ghcr.io/eloiblt/ubuntu-custom-image:${{ steps.version_step.outputs.semVer }}:latest