name: CI - CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://ghcr.io -u eloiblt --password-stdin

      - name: Build
        working-directory: .
        run:
          docker build -t ghcr.io/eloiblt/ubuntu-custom-image  .

      - name: Push
        working-directory: .
        run: docker push ghcr.io/eloiblt/ubuntu-custom-image